[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "deteccion"
version = "0.1.0"
requires-python = ">=3.10"
# ultralytics ya trae torch, opencv, matplotlib, numpy y pyyaml
dependencies = ["ultralytics>=8.3.0", "pandas"]

[project.optional-dependencies]
kaggle = ["kaggle"]
dev = ["nbstripout"]
